### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-rewards#1]
See README

**Comment by j3k0** [comment]
@elmigranto Just making sure you see this one top of your list on waffle (since we had such an issue with private repositories already)

**Comment by elmigranto** [comment]
So the idea is when someone logs in into App B, we may want to award him "100 App A coins" if these conditions are met:

  1. `userId` has App A login;
  1. `userId` was not awarder before.

Question about first one…

> * Then load app-1's "auth" usermeta key.
> * If it is falsy, do nothing else with this event.

My understanding is that this is usermeta value specific to App A (something like last login timestamp or similar) . But it looks suspiciously like auth token (which is a) lives in directory and b) shared across all apps), so I just want to make sure that it's not :)

**Comment by elmigranto** [comment]
I am also a bit concerned about "truthy" / "fasly" part, my guess would be because usermeta does not allow to delete values, only overwrite them, so we write empty strings? Do we actually do this?

For now I am checking [reply](https://github.com/j3k0/ganomede-usermeta#get-authtokenkeys) for presence of a key (`reply[userId].hasOwnProperty(metaName)`), since we [return empty objects on missing keys or users](https://github.com/j3k0/ganomede-usermeta/blob/master/tests/usermeta.router.test.js#L72). Not sure if this is correct, for now I assume empty string can be a legitimate value.

**Comment by elmigranto** [comment]
Also, README specifies virtual currency addresses for both apps, and says we should post reward to virtual currency ***2***. I take it as a mistake:

  - we only need vcurrency ***1***;
  - we post reward to that.

**Comment by j3k0** [comment]
OK, first of, to clarify my thoughts I drew this:

![rewards links](https://cloud.githubusercontent.com/assets/191881/24584959/27d14340-1788-11e7-827f-575d25c24093.png)

> award him "100 App A coins" if:
>  - userId has App A login;
>  - userId was not awarder before.

Yes

> My understanding is that this is usermeta value specific to App A (something like last login timestamp or similar) . But it looks suspiciously like auth token (which is a) lives in directory and b) shared across all apps), so I just want to make sure that it's not :)

`auth` usermeta is specific to each app. It's a timestamp that says the last time the user logged in into this app.

> I am also a bit concerned about "truthy" / "fasly" part, my guess would be because usermeta does not allow to delete values, only overwrite them, so we write empty strings? Do we actually do this?

I'm not sure if your concern is about security? `auth` is a private metadata, so it can only be written by server modules using `API_SECRET`.

> [...] for now I assume empty string can be a legitimate value.

`usermeta` doesn't allow deleting keys (has never been necessary so far). Yes, an empty string can be considered falsy.

> Also, README specifies virtual currency addresses for both apps, and says we should post reward to virtual currency 2. I take it as a mistake

Yes it was a mistake.

**Comment by j3k0** [comment]
BTW, looking at the graph, I wonder why we would need a link "**Rewards &rarr; app2.usermeta**". I guess the `$reward` usermeta could as well be written to **app1.usermeta**, then we can get rid this link (which removes one reason for failure).

Right? If so, let's go for it.

**Comment by elmigranto** [comment]
> > "truthy" / "fasly" part
>
> I'm not sure if your concern is about security?

What I mean is that `0` or `''` could theoretically be valid usermeta values. I'm not sure if that's the case with any of our values right now, though. So I made "having a key" check be `hasOwnProperty` (effectively, redis' [`EXISTS`](https://redis.io/commands/exists)). If that's the problem, let me know.

Yeah, we can delete `app2.usermeta`.
